fix: revise  markdown errors
open-sauced/docs pull request #107
Opened 2023-06-18 19:30 UTC by CBID2

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR fixes the Markdown errors found in one of the docs. 
## Related Tickets & Documents

Fixes #106 
## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [X] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?
![Looks good to me](https://github.com/open-sauced/docs/assets/105683440/b7753741-1a30-4839-bd9e-68d0cb52c0ec)

2023-06-19 22:07 UTC, BekahHW commented on docs/introduction.md
> +Eager to get started? Check out[the Effectively Highlights section in our free "Intro to Open Source" course](https://github.com/open-sauced/intro/blob/main/06-the-secret-sauce.md#effectively-highlig
I would add the full title here:

> Check out the "Effectively Highlight Your Contributions" section...

2023-06-19 22:25 UTC, CBID2 commented
Made the change @BekahHW! :)

2023-06-27 20:57 UTC, bdougie requested changes

2023-06-27 20:57 UTC, bdougie commented on docs/introduction.md
> +
These sections are not needed in this PR. Everything else looks great

2023-07-03 14:58 UTC, bdougie commented on docs/introduction.md
> +
```suggestion
```

2023-07-03 14:59 UTC, bdougie approved these changes

2023-07-03 15:00 UTC, merged