docs: adding a gif of doing a highlight on the website
open-sauced/docs pull request #137
Opened 2023-08-18 01:18 UTC by CBID2

## Description
This PR adds a GIF demonstrating how to post a highlight on OpenSauced without the Chrome extension.

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #110 
## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [X] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-08-18 01:39 UTC, bdougie requested changes

2023-08-18 01:39 UTC, bdougie commented on static/gif/highlight-explain.gif
Can you create a new one with the loom timer and avatar?

https://gif.ski/ is an option.

2023-08-18 02:12 UTC, CBID2 commented on static/gif/highlight-explain.gif
Made the necessary changes @bdougie

2023-08-19 19:19 UTC, bdougie requested changes
We need a gif in a smaller size. Consider zooming in on the screen.

2023-08-19 23:48 UTC, CBID2 commented
> We need a gif in a smaller size. Consider zooming in on the screen.

How's this one @bdougie:
![highlights-demo](https://github.com/open-sauced/docs/assets/105683440/6e544006-54cd-4167-baf5-4ed8f5489c02)

2023-08-21 16:18 UTC, bdougie commented
> > We need a gif in a smaller size. Consider zooming in on the screen.
> 
> How's this one @bdougie: ![highlights-demo](https://user-images.githubusercontent.com/105683440/261824363-6e544006-54cd-4167-baf5-4ed8f5489c02.gif)

Can you turn off the grammarly

2023-08-21 16:45 UTC, CBID2 commented
> > > We need a gif in a smaller size. Consider zooming in on the screen.
> 
> > 
> 
> > How's this one @bdougie: ![highlights-demo](https://user-images.githubusercontent.com/105683440/261824363-6e544006-54cd-4167-baf5-4ed8f5489c02.gif)
> 
> 
> 
> Can you turn off the grammarly 

Sure

2023-08-21 20:01 UTC, CBID2 commented
> > > We need a gif in a smaller size. Consider zooming in on the screen.
> > 
> > 
> > How's this one @bdougie: ![highlights-demo](https://user-images.githubusercontent.com/105683440/261824363-6e544006-54cd-4167-baf5-4ed8f5489c02.gif)
> >       
> >         [
> >           
> >         
> >             ![highlights-demo](https://user-images.githubusercontent.com/105683440/261824363-6e544006-54cd-4167-baf5-4ed8f5489c02.gif)
> >           ](https://user-images.githubusercontent.com/105683440/261824363-6e544006-54cd-4167-baf5-4ed8f5489c02.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/105683440/261824363-6e544006-54cd-4167-baf5-4ed8f5489c02.gif)
> 
> Can you turn off the grammarly

How about this one @bdougie?
 
![posting-highlight-demo](https://github.com/open-sauced/docs/assets/105683440/aa6db15f-176c-4a5d-a5a8-0bc48f28a855)

2023-08-25 20:21 UTC, CBID2 commented
> The current gif shows a lot of typing. Can you make the recorded action you pasting the PR URL and clicking the auto-summary button.
> 
> Think of this like a commercial with only 5 seconds to convince the suer to try this feature. We don't need to show the user how to type their own summary, but rather we can sell them on generating a summary.
How's this one @bdougie:  
![highlights-demo](https://github.com/open-sauced/docs/assets/105683440/65c5298a-b338-493c-a6d2-7dc6ba84c8d3)

2023-08-25 21:28 UTC, bdougie commented
This gif is much better.

2023-08-25 21:52 UTC, CBID2 commented
> This gif is much better.

Done

2023-08-26 01:29 UTC, CBID2 commented
Is this the PR you're revising @bdougie?

2023-08-26 02:59 UTC, bdougie commented
No, but this gif is still big. Currently 2.6mb

2023-08-26 04:06 UTC, CBID2 commented
> No, but this gif is still big. Currently 2.6mb

Ok I'll find a way to shrink it @bdougie

2023-09-06 17:36 UTC, bdougie submitted a review, later dismissed
cropping of gif makes it not viewable.

2023-09-06 17:36 UTC, bdougie commented on static/gif/highlights-demo.gif
Looking at this and it is cropped on the wrong place. 

![Screen Shot 2023-09-06 at 10 35 52 AM](https://github.com/open-sauced/docs/assets/5713670/81f24e7e-7046-464f-9a50-d92d41a057dd)

2023-09-06 18:50 UTC, CBID2 commented
> cropping of gif makes it not viewable.

Noted

2023-09-07 22:51 UTC, CBID2 commented
> > cropping of gif makes it not viewable.
> 
> Noted
How about now @bdougie: 
![highlight](https://github.com/open-sauced/docs/assets/105683440/22b3acf1-7bc9-49a1-9cd9-5442d6059113)

2023-09-07 22:54 UTC, bdougie commented
> How about now @bdougie:

So much better

2023-09-10 23:59 UTC, CBID2 commented
> > How about now @bdougie:
> 
> So much better

Hey @bdougie. I made the change

2023-09-12 15:49 UTC, BekahHW approved these changes

2023-09-12 15:50 UTC, BekahHW commented
<img src="https://media3.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

2023-09-12 15:50 UTC, merged