docs: adding an explainer page and GIF on insight pages
open-sauced/docs pull request #138
Opened 2023-08-18 19:28 UTC by CBID2

## Description
This PR adds an explainer page and GIF about the insights page. This 
would help new users gain a better understanding on how to use this feature on OpenSauced.  

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #110 
## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [X] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-08-19 19:18 UTC, bdougie requested changes

2023-08-19 19:18 UTC, bdougie commented on docs/community/insight-pages.md
> +You know how you see the delicious looking images of pizza pies in the menu when you first walk in a pizza shop? Well, we wanted to replicate this feeling with our Insight pages. This feature is wher
The tone is nice, but will be hard to translate the first sentence if we end up doing that in the future. Probably just go with the last sentence.

2023-08-19 19:18 UTC, bdougie commented on static/gif/insight-pages-demo.gif
The gif size 6mb. The other gifs are around 70kb. We will need a smaller gif. I also suggest short short in duration. You can cut out frames and typing to make it smaller and faster.

2023-08-19 21:36 UTC, CBID2 commented on static/gif/insight-pages-demo.gif
Ok

2023-08-19 21:46 UTC, CBID2 commented on static/gif/insight-pages-demo.gif
How's this one @bdougie:
 
![insight-page-demo](https://github.com/open-sauced/docs/assets/105683440/97b00f8a-8d13-4de4-a18b-d0a26749400f)

2023-08-22 13:43 UTC, bdougie commented on static/gif/insight-pages-demo.gif
It's ok. I can't tell the size without it being committed. The most impactful 5 seconds are at the end, where you show the user the repository being added. I'd suggest cutting it down to only that moment. There is a lot dead time watching typing at the moment and it is not useful.

2023-08-22 14:12 UTC, CBID2 commented on static/gif/insight-pages-demo.gif
Thanks @bdougie. The size is 606KB

2023-08-25 21:27 UTC, bdougie commented
@CBID2 can you add the gif back to the PR? We can move forward with this.

2023-08-25 22:01 UTC, CBID2 commented
> @CBID2 can you add the gif back to the PR? We can move forward with this.

Done with this and #137 too @bdougie

2023-08-25 23:12 UTC, bdougie approved these changes

2023-08-25 23:12 UTC, merged