feat: Add maintainers-guide
open-sauced/docs pull request #177
Opened 2023-09-27 18:17 UTC by BekahHW

## Description

 closes #165

- Creates a separate file for being a maintainer

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-09-27 19:50 UTC, nickytonline requested changes
This looks good to me. One small change request. Thanks for writing this up @BekahHW!

2023-09-27 19:50 UTC, nickytonline commented on docs/maintainers/maintainers-guide.md
> +- Providing comments and responses on PRs, issues, discussions, and Discord messages.
docs (blocking): explain the acronym before using it.

```suggestion
- Reviewing and merging pull requests (PRs).
- Providing comments and responses on PRs, issues, discussions, and Discord messages.
```

2023-09-27 20:50 UTC, nickytonline approved these changes
Thanks for making the change @BekahHW! 🚢

2023-09-28 00:12 UTC, CBID2 commented on docs/maintainers/maintainers-guide.md
> +Welcome to OpenSauced, Maintainers Guide for contributors who are interested in being part of the maintainer team for OpenSauced repositories.
[proofreading] This is a great start @BekahHW! :) Just omit the parts I suggested below so the paragraph can be clearer. 
```suggestion
Welcome to OpenSauced! This guide is for contributors who are interested in being part of the maintainer team!  
```

2023-09-28 00:18 UTC, CBID2 commented on docs/maintainers/maintainers-guide.md
> +- Prove your pizza worth!
[nitpick: While "prove your pizza worth" can be humorous, it implies that a person is not worthy to join if they don't contribute enough, which can turn some people away. It also goes against your goal to make more inclusive documentation. 
```suggestion
- Join our [Discord community](https://discord.com/invite/U2peSNf23P). 
- Be involved!
```

2023-09-28 00:23 UTC, CBID2 requested changes
Hi @BekahHW! :) The guide is off to a great start! :) I just gave some suggestions and asked some questions to help you improve it.

2023-09-28 00:23 UTC, CBID2 commented on docs/maintainers/maintainers-guide.md
> +Thank you for your interest in becoming a maintainer! Please reach out if you need help, guidance, or clarification at any time.
[question/suggestion] Who can people contact if they are interested in being a maintainer? Consider adding this information to make the CTA clearer.

2023-09-28 04:15 UTC, merged