feat: adding page about hacktoberfest
open-sauced/docs pull request #179
Opened 2023-09-28 21:25 UTC by CBID2

## Description
This PR adds a page about Hacktoberfest, helping people who are new to open source understand the benefits of joining the event.

_Generated using [OpenSauced](https://opensauced.ai/)._

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Closes #168 

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [X] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-09-28 22:55 UTC, BekahHW requested changes
This is a great overview. I think we could add a section about "What to expect during Hacktoberfest"

That should include info on being patient with maintainers, recognizing maintainers are people with lives outside of open source, and the importance of making meaningful contributions.

2023-09-28 22:55 UTC, BekahHW commented on docs/community/dev-card.md
> +
Looks like you accidentally added a space here.

2023-09-28 22:55 UTC, BekahHW commented on docs/community/hacktoberfest.md
> +This event is a great way to jumpstart your journey in open source, to meet other people in the tech community, and build your skills. Curious to learn more about the value of contributing to open so
Identifying names in documentation can be disruptive due to the shift in style. Let's do this instead:

Check out these resources:
- [Hacktoberfest 2023: Beyond Green Squares](https://dev.to/opensauced/hacktoberfest-2023-beyond-green-squares-4d6j) to learn how to make this a meaningful Hacktoberfest focused on growth, impact, and building relationships.
- [Setting Goals for Your Open Source Contributions](https://dev.to/opensauced/setting-goals-for-your-open-source-contributions-349b) for resources on how to grow your experience through open source.

2023-09-28 22:55 UTC, BekahHW commented on docs/community/hacktoberfest.md
> +
Give instructions on how to join Hacktoberfest. This should include a link to sign-ups and basic instructions (4 PRs from Oct. 1-31 in repos opted into Hacktoberfest).

2023-09-28 23:43 UTC, CBID2 commented
> maintainers are people with lives outside of open source

Made the changes @BekahHW! :)

2023-10-02 15:58 UTC, BekahHW approved these changes

2023-10-02 16:05 UTC, merged