bug : fixes merge conflict
open-sauced/docs pull request #211
Opened 2023-11-20 22:54 UTC by Lymah123

## Description
- This PR fixes merge conflicts and updates conflicting files (#210).

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-11-20 22:59 UTC, Lymah123 commented
Hi @BekahHW and @CBID2 , I fixed the conflicting files with this PR.

2023-11-20 23:38 UTC, Lymah123 commented
Hi, @BekahHW and @CBID2, you can now review. I will be waiting!

Thank you.

2023-11-21 02:15 UTC, CBID2 commented
> Hi @BekahHW and @CBID2 , I fixed the conflicting files with this PR.

Hi @Lymah123. Can you add the issue number to the `Related Documents and Tickets" section instead of the Description?

2023-11-21 02:20 UTC, CBID2 approved these changes
Looks great @Lymah123! :)

2023-11-21 10:13 UTC, Lymah123 commented
> > Hi @BekahHW and @CBID2 , I fixed the conflicting files with this PR.
> 
> Hi @Lymah123. Can you add the issue number to the `Related Documents and Tickets" section instead of the Description? It'll make it easier for the PR and issue to close.

Hi @CBID2,  how do you mean? I didn't get that.

2023-11-21 11:27 UTC, adiati98 commented
@Lymah123 you added a [setting-up-a-new-repository.md](docs/maintainers/setting-up-a-new-repository.md) here. I don't think that it is part of the newest Maintainer section.

@BekahHW can you confirm this?

2023-11-21 12:25 UTC, adiati98 commented on docs/contributing/technical/resolve-merge-conflicts.md
> +## Repository setup
@Lymah123 There is a duplication of this title in line 19. Which one do you want to keep?

2023-11-21 12:41 UTC, adiati98 requested changes
Hi @Lymah123,
I've left some feedback for you here. :)

2023-11-21 12:41 UTC, adiati98 commented on docs/community/glossary.md
> +The PR Velocity measures the percentage and amount of days that pull requests that are merged. It is a great way to track the progress of your open source contributions.
Let's add a space between the title and paragraph here.
Besides that it is the [best practice](https://www.markdownguide.org/basic-syntax/#heading-best-practices), we will do this going forward for consistency.

```suggestion
## PR Velocity

The PR Velocity measures the percentage and amount of days that pull requests that are merged. It is a great way to track the progress of your open source contributions.
```

2023-11-21 13:35 UTC, Lymah123 commented
> @Lymah123 you added a [setting-up-a-new-repository.md](docs/maintainers/setting-up-a-new-repository.md) here. I don't think that it is part of the newest Maintainer section.
> 
> @BekahHW can you confirm this?

Hi @adiati98 , I didn't change anything from that file.  I only touched it due to merge conflicts I had.

2023-11-21 14:02 UTC, closed without merging