Updated docs to retrieve auth token
open-sauced/docs pull request #280
Opened 2024-03-18 16:28 UTC by OmkarPh

## Description
This PR updates docs to copy the auth token

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
https://github.com/open-sauced/hot/pull/514

## Mobile & Desktop Screenshots/Recordings

## Steps to QA

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-03-18 17:16 UTC, adiati98 commented
Hi @OmkarPh 

First of all, thank you for the PR! ✨️
I see that this PR is related to an issue in our hot repo.

However, an issue to update the docs is required for you to make any changes in this repo. Can you please create an issue for the purpose of updating the docs?

Based on [our guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#pull-requests-pr), PRs without link to any issue will be closed. And for that reason, we're closing this PR.

Feel free to create a new PR or ask us to reopen this PR once there's an issue accompanying the PR.

Also, we would like to confirm this changes/update from the @open-sauced/engineering team.

Thank you! 😊

2024-04-03 18:49 UTC, adiati98 commented
Hi @OmkarPh,

I've reopened your PR.

Please update the PR form as follow:

- Let's make the description more descriptive:

   > This PR updates the docs from "Print auth token" to "Copy auth token" based on changes at https://github.com/open-sauced/hot/pull/514.
- Link your issue in the "Related Tickets and Documents" section instead of description.
- As you can see, there's a bot here mentioning [issue reference](https://github.com/open-sauced/docs/pull/280#pullrequestreview-1943601660) as part of PR complience. That's because GitHub only receives [particular keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). So, please use the prefix `Closes` when linking your issue.

2024-04-03 19:03 UTC, adiati98 requested changes
Hey @OmkarPh,

I left a review here to be fixed. Thanks! 🙂

2024-04-08 16:27 UTC, OmkarPh commented on docs/contributing/set-up-authentication.md
> +2. Click on the **Copy auth token** option to copy your auth token to clipboard
Thanks for the review !

I've made the changes

2024-04-09 20:15 UTC, adiati98 approved these changes
It looks good to me.
But I would like to have @BekahHW and @nickytonline second opinion on the content. 🙂

2024-04-11 17:56 UTC, BekahHW approved these changes

2024-04-11 19:34 UTC, merged