feat: update contributing guide
open-sauced/docs pull request #288
Opened 2024-03-28 19:29 UTC by adiati98

## Description

This PR updates contributing guide with the following changes:

- Rewording an instruction to emphasize that creating a new branch is a must.
- Add an information that maintainers may unassign contributors and close their PR if they take more than one `good first issue`.
- Add Docusaurus special admonition syntax to highlight notes, infos, etc.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #287 

## Mobile & Desktop Screenshots/Recordings

### Before

![Before applying admonition syntax](https://github.com/open-sauced/docs/assets/45172775/d6f50c2b-cd73-445f-9f81-a2b3313591d9)

### After

![Admonition highlight](https://github.com/open-sauced/docs/assets/45172775/27f6060e-82e3-4054-95a1-0385df051028)

## Steps to QA

1. Pull this branch.
2. Run the project locally.
3. Go to http://localhost:3000/contributing/introduction-to-contributing/

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-03-28 19:36 UTC, adiati98 commented
@BekahHW I have a note here.

The syntax for the "danger" one is actually `warning` (line 87). But it somehow renders as danger. It should be rendered as warning like on the [Docusaurus docs](https://docusaurus.io/docs/markdown-features/admonitions).
 
Hopefully, updating the Docusaurus in the future will resolve this. I included screenshots of before and after in the PR form. So, if you want me to change the "danger" to what we had previously, please let me know.

Thanks!

2024-04-03 12:49 UTC, BekahHW requested changes
Just a couple of things to break up the special notes.

2024-04-03 12:49 UTC, BekahHW commented on docs/contributing/introduction-to-contributing.md
> +:::note
I think the back to back "special" blocks might be too much. Let's leave the note as is, esp bc it's more for maintainers and not necessarily something contributors really need.

2024-04-03 12:49 UTC, BekahHW commented on docs/contributing/introduction-to-contributing.md
> +**IMPORTANT** <br /> Please do not DM Maintainers or contact them outside of GitHub if you want a PR Review. If you haven't received a review within a week, please tag them in the PR comments to ask
Let's move this to the community section right below where we mention joining Discord.

2024-04-03 18:10 UTC, adiati98 commented
@BekahHW I made the changes here based on your suggestions.
One note, I moved the note for maintainer as part of point 9 as below screenshot because it talks about PR form. So, it make more sense to have this note as part of this point. But let me know if you want me to move it back to after the warning (danger) highlight. :)

![note for maintainers](https://github.com/open-sauced/docs/assets/45172775/a73c72ab-a1ca-4108-b9e9-d835f49ffb78)

2024-04-04 18:38 UTC, BekahHW approved these changes

2024-04-04 18:38 UTC, merged