feat: 100 days of oss
open-sauced/docs pull request #99
Opened 2023-06-15 16:23 UTC by BekahHW

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
Add #100DaysOfOSS challenge to OpenSauced community docs. The challenge is flexible and participants can join in whenever they're ready. The PR adds a new file `100-days-of-oss.md` and updates `sidebars.js`. 

_Generated using [OpenSauced](https://opensauced.ai/)._

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-06-15 18:03 UTC, bdougie approved these changes
I really love this and will add a slide to my OSCA keynote on this as well. This will be an amazing onramp for so many new and first time contributors. 

Thanks for putting this together @BekahHW

2023-06-16 05:07 UTC, CBID2 requested changes
Hi @BekahHW! I know I gave you my review via DMs, but I found the PR, so I decided to give more feedback. I hope you find my suggestions helpful. 😃

2023-06-16 05:07 UTC, CBID2 commented on docs/community/100-days-of-oss.md
> +
[Addition] I think there should be a section on balancing this challenge here. One of the criticisms I heard about 100 Days of Code is that implies this needs to be done for 100 days straight,so putting something like "take breaks" or "reward yourself for doing something OSS-related" would help students to participate.

2023-06-16 05:07 UTC, CBID2 commented on docs/community/100-days-of-oss.md
> +
[Nitpick] I'd mention something like tuition-fee free. It’ll pique new contributor’s interest.

2023-06-17 12:48 UTC, CBID2 approved these changes
LGTM! :)

2023-06-17 12:55 UTC, merged